### ISSUE TITLE
Define a asuka callback function

### ISSUE THREAD

**Issue by efraimrodrigues** [Flutterando/asuka#12]
I often use asuka to display error messages and these are related to exceptions most of the time. 

I feel like it'd be useful to have a handler function called in these situations. For instance, I'd like to have these exceptions logged in my backend application with the stack trace and other details. It'd allow me to be address the error with all the details involved at the exact moment it'd happen.

**Comment by efraimrodrigues** [comment]
I'm not sure this is the best approach to solve this. But I've just submitted PR #13  implementing this. 

Here's an example code:

![code](https://user-images.githubusercontent.com/12123918/113586831-61d02a80-9604-11eb-9ea2-353069c4ad58.png)

![code1](https://user-images.githubusercontent.com/12123918/113586696-30eff580-9604-11eb-894d-e8aa83342156.png)

**Comment by jacobaraujo7** [comment]
LGTM
