### ISSUE TITLE
Adicionar um metodo asuka.pop() sem context

### ISSUE THREAD

**Issue by TRONEducation** [Flutterando/asuka#14]
O modular.to.showDialog funcionava com o Modular.to.pop()
agora temos o asuka.showDialog() sem cotexto mas não temos um asuka.pop()
Eu tentei o asuka.showDialog() com o Modular.to.pop() mas não funciona.

Se eu estiver em um metodo que não tem contexto seria bom um asuka.pop() se não eu teria que passar por parametro o contexto do dialog em varios metodos.

**Comment by Bwolfs2** [comment]
Modular.to.showDialog worked with Modular.to.pop ()
now we have asuka.showDialog () with no text but we don't have an asuka.pop ()
I tried asuka.showDialog () with Modular.to.pop () but it doesn't work.

If I am in a method that has no context, an asuka.pop () would be good, otherwise I would have to pass the parameter of the dialog in various methods.

**Comment by marcellocamara** [comment]
@TRONEducation tive este mesmo problema, 
não consegui dar pop em um dialog invocado pelo **asuka** (no meu caso com contexto), 
tentei via `Modular.to.pop` mas ele fecha a tela de trás.... só consegui com `Navigator.pop(context);`.

**Comment by marcusrohden** [comment]
if you pass the context from asuka into the widget you want to show, you can use Navigator.of(context).pop(); and it will dismiss your dialog or modal bottom sheet.

```
asuka.showBottomSheet((context) {
                          return _buildEditPermissionsBottomSheet(
                            context,
                            widget.listVenues[index],
                          );
                        });
```


and then I got this button on my widget that makes use from context generated above on asuka:

```
ElevatedButton(
                    onPressed: () {
                      print('tap on confirm');
                      Navigator.of(context).pop();
                    },
                    child: Text('Confirm'),
                  ),
```

**Comment by YOUDevelop** [comment]
Same problem

**Comment by toshiossada** [comment]
Same problem

**Comment by gopbarbosa** [comment]
Mesmo problema

**Comment by gopbarbosa** [comment]
Utilizando o comentário do @marcuslindemannrohden obtive a solução abaixo.  
Acredito que possa funcionar de forma paliativa.  

```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:asuka/asuka.dart' as asuka;

class Alert {
  late BuildContext context;

  Alert();

  void showAlert({
    final Text? title,
    final Widget? content,
    final List<Widget>? actions,
  }) {
    asuka.showDialog(
      builder: (c) {
        context = c;
        return AlertDialog(
          title: title,
          content: content,
          actions: actions,
        );
      },
    );
  }

  void dismissDialog() {
    Navigator.of(context).pop();
  }
}

```

E na utilização ficou 

```
  Alert alert = Alert();
    alert.showAlert(
      title: Text('Erro'),
      content: Text('Ocorreu um erro ao encontrar o usuario.'),
      actions: <Widget>[
        TextButton(
          onPressed: () => {
            alert.dismissDialog(),
          },
          child: Text('Ok'),
        ),
      ],
    );
  }
```

**Comment by gopbarbosa** [comment]
Eu tive um problema com a solução acima pois o asuka.showDialog é uma função assíncrona que é acionada no momento do fechamento do dialog e não existe uma forma de observar a abertura do dialog. Logo se ocorrer uma exibição e fechamento muito rápido do dialog a variável context seria null.

**Comment by mayconight** [comment]
@GarbielBarbosa, implementei algo nesse mesmo sentido e tive o mesmo problema aqui. Abro um showDialog e tenho um método que, embora assíncrono, se resolve rapidamente em uma determinada situação, inviabilizando essa solução, pois o context ainda está nulo.

**Comment by gopbarbosa** [comment]
@mayconight Então resolvi essa questão de uma maneira nao muito legal. Mas funcionou ..... 
Inclui um  Future.delayed antes de realizar o  Navigator.pop. 
Ficou assim

```
Future<void> hide() async {
    await Future.delayed(Duration(milliseconds: 100));
    Navigator.pop(context);
  }
```

**Comment by danteCarvalho** [comment]
Nossa faz tempo qui abri essa issue... eu criei uma lista que centraliza os contexts dos Dialogs.
List<BuildContext> contexts = [];

chamo o dialog assim 
```dart
dialog(Widget dialog) {
    asuka.showDialog(
      builder: (context) {
        contexts.add(context);
        return dialog;
      },
    );
  }
```

e remove o ultimo Dialog ativo assim
```dart
pop() async {
    var list = [];
    for (var obj in contexts) {
      try {
        obj.size;
      } catch (e) {
        list.add(obj);
      }
    }
    for (var obj in list) {
      contexts.remove(obj);
    }
    Navigator.of(contexts.removeLast()).pop();
  }
```

**Comment by MarioCarlosChita** [comment]
Hey @Bwolfs2  como fica o asuka como o Modular visto que devemos usar o Material.router e não tem o 
 navigatorObservers: [
       asuka.asukaHeroController //if u don`t add this Hero will not work
    ],

**Comment by Bwolfs2** [comment]
@MarioCarlosChita  Tem sim ```Modular.setObservers([suka.asukaHeroController]);```
