### ISSUE TITLE
No named parameter with the name 'constraints'

### ISSUE THREAD

**Issue by silasrm** [Flutterando/asuka#17]
Estou tentando utilizar no Flutter 2.2.3 e está dando este erro:

```
.pub-cache/hosted/pub.dartlang.org/asuka-2.0.0+1/lib/src/asuka_singleton.dart:202:5: Error: No named parameter with the name 'constraints'.
[        ] [        ]     constraints: constraints,
[        ] [        ]     ^^^^^^^^^^^
[        ] [        ] /home/####/fvm/versions/2.2.3/packages/flutter/lib/src/material/bottom_sheet.dart:649:12: Context: Found this candidate, but the arguments don't match.
[        ] [        ] Future<T?> showModalBottomSheet<T>({
[        ] [        ]            ^^^^^^^^^^^^^^^^^^^^
```

Alguém sabe se tem como resolver ou tenho que mudar a versão do Flutter?

**Comment by tauamendonca** [comment]
Isto ocorre devido a uma mudança do showModalBottomSheet<T> no Flutter para a inclusão de constraints ocorrida na versão 2.3.0 do Flutter (commit de 21/Abr/2021), que levou a necessidade de correção do commit 4a447eb e se tornou uma Breaking Change para o Asuka, que na sua versão 2.0.0+1 parou de funcionar para as versões de Flutter pré 2.3.0. 

![image](https://user-images.githubusercontent.com/63937691/181618375-3f1e123c-4e5d-42c3-a0c0-00c2b540a9d6.png)

Solução/Solution:  Utilizar a versão 2.0.0 ou menor do Asuka  /   Use version 2.0.0 or lower of Asuka.  Versions 2.0.0+1 or above will only work with Flutter 2.3.0 or newer.

**Comment by silasrm** [comment]
Opa. Não posso testar mas que bom que resolveu. Vou fechar!
