### ISSUE TITLE
Cannot dismiss existing snackBars

### ISSUE THREAD

**Issue by animalnots** [Flutterando/asuka#18]
Currently it's not possible to hide existing snackbar so it adds new ones to the queue.
Please add possibility to remove or hide existing snackbars, thanks.
References:
https://api.flutter.dev/flutter/material/ScaffoldMessengerState/hideCurrentSnackBar.html
https://docs.flutter.dev/release/breaking-changes/scaffold-messenger

**Comment by gustavorw** [comment]
tried to use: ```  asuka.hideCurrentSnackBar();``` @animalnots

**Comment by animalnots** [comment]
will check it out, thanks!
