### ISSUE TITLE
Asuka not working with FluentUI

### ISSUE THREAD

**Issue by JesusMayuri7** [Flutterando/asuka#19]
![image](https://user-images.githubusercontent.com/13004243/174171918-2523a0a7-8d88-41ff-aaba-4db3b272dcc7.png)
![image](https://user-images.githubusercontent.com/13004243/174172048-7219d53e-d882-43f5-84d4-825b486fb7db.png)
![image](https://user-images.githubusercontent.com/13004243/174172126-2bf44568-abb0-425c-8fc1-451702a769c0.png)

**Comment by Bwolfs2** [comment]
I guess u forget to add the ```builder: asuka.builder```
