### ISSUE TITLE
Erro ao compilar o projeto utilizando a lib

### ISSUE THREAD

**Issue by leonardopaim** [Flutterando/asuka#2]
Utilizo atualmente a versão 1.17.4 do Flutter e ao tentar compilar o projeto recebo um erro informando que os parâmetros `barrierColor` e `useSafeArea` não existem.

Clonei o `asuka` e o `flutter` para entender o que estava acontecendo e vi que na versão 1.17.4 esses 2 parâmetros não existem ainda. Eles foram implementados [neste commit](https://github.com/flutter/flutter/commit/d35ade4a6c1aa2dadb2af388f716ac4e8aa715d6) que é uma versão posterior até onde entendi.

Para reproduzir o problema basta abrir o projeto do `asuka` com o flutter 1.17.4 que a classe `asuka_singleton` será sinalizada com erro nesses parâmetros.

**Comment by leonardopaim** [comment]
Como solução temporária para esse problema precisei fixar a versão da lib para a `1.0.0` removendo o `^` da declaração da versão no meu `pubspec.yaml`

Aparentemente foi utilizado um canal diferente do `stable` e nele existe alguns parâmetros que não existem ainda no flutter atual estável.

Minha solução no momento:
```yaml
dependencies:
  asuka: 1.0.0
```

**Comment by Ascenio** [comment]
Parece que esses parâmetros são da versão `1.21.0-1.0.pre`. Por hora acho que seria uma boa remover, adicionando mais tarde quando essa 1.21 se tornar a stable.

**Comment by jacobaraujo7** [comment]
estou arrumando aqui para a stable. Obrigada pelo suporte
