### ISSUE TITLE
how to adjust popup size?

### ISSUE THREAD

**Issue by DEVigodE** [Flutterando/asuka#35]
Is it possible to adjust popup size? Because I'm trying to use it in flutter web, it's getting disproportionate to the screen size.

⬇️ It's like this currently ⬇️
![image](https://user-images.githubusercontent.com/13280820/206194551-290d60a4-c2fe-4467-825a-95362bb4c81b.png)

⬇️ I wanted something like this ⬇️
![image](https://user-images.githubusercontent.com/13280820/206195025-5a4835b6-1f54-4534-9886-baf40dbc5709.png)

**Comment by shobhit0888** [comment]
can i work on this

**Comment by shobhit0888** [comment]
@ZIBMBRAZIL can I work on this issue, I have good experience with flutter.

**Comment by Bwolfs2** [comment]
Add in the version 2.0.2
