### ISSUE TITLE
Asuka broken on Beta / Master

### ISSUE THREAD

**Issue by tlvenn** [Flutterando/asuka#38]
```
../../.pub-cache/hosted/pub.dev/asuka-2.0.2/lib/src/asuka_singleton.dart:345:29: Error: The argument type 'bool?' can't be assigned to the parameter type 'bool' because 'bool?' is nullable and 'bool' isn't.
      semanticsDismissible: semanticsDismissible,
                            ^
Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **
```

**Comment by tauamendonca** [comment]
@jacobaraujo7 happening on iOS

**Comment by FelCarv01** [comment]
I attempted to simulate this issue on iOS, but the issue did not occur.
Please provide further information on how the problem occurred.
@tlvenn

**Comment by inceptusp** [comment]
@FelCarv01 just upgrade flutter and try to run a project that uses asuka

**Comment by rodja** [comment]
I also experience the issue. Is there a workaround?

**Comment by willianbrun** [comment]
Same here

**Comment by willianbrun** [comment]
Here`s a workaround:

At the path: ../../.pub-cache/hosted/pub.dev/asuka-2.0.2/lib/src/asuka_singleton.dart:335:10

Change line 335:
`bool? semanticsDismissible,`

to: 

`bool semanticsDismissible = true,`.

Hope u aren't using "showCupertinoModalPopup", because it will have unexpected behavior
