### ISSUE TITLE
Extra arguments error, flutter 3.19

### ISSUE THREAD

**Issue by marcusrohden** [Flutterando/asuka#44]
Currently getting an error on Asuka dependency when I try to run one of my projects with the new Flutter 3.19.0 version.

`Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/asuka-2.2.0/lib/src/asuka_singleton_deprecated.dart:104:10: Error: Expected 0 type arguments.
`

**Comment by marcusrohden** [comment]
Just submitted a pull request fixing it

#45

**Comment by jacobaraujo7** [comment]
fixed
